// Magic-link + OTP lifecycle.
//
// P5: each request now creates a row with:
//   - token (cuid2)        — magic-link URL token
//   - pairToken (UUID)     — generated by the requesting browser; pairs the
//                            click in any email client back to that browser
//   - code (6 digits)      — OTP fallback for users whose email link opens
//                            in an in-app browser (QQ Mail / Gmail / WeChat)
//   - paired, consumed     — single-use enforcement
//
// The verify route marks `paired=true` BEFORE the row gets consumed by
// signIn's authorize callback (which sets consumed=true). This lets
// browser A's /api/auth/pair-status polling see the pairing and issue
// a session cookie for the polling browser, even though browser B
// (the email viewer) is the one that actually clicked the link.

import { createId } from '@paralleldrive/cuid2'
import prisma from './prisma'

const TOKEN_TTL_MS = 10 * 60 * 1000   // 10 minutes (was 15 — trimmed for tighter UX)

export type ConsumeResult =
  | { ok: true; identifier: string }
  | { ok: false; reason: 'not-found' | 'expired' | 'already-consumed' }

// Generate a cryptographically-random 6-digit code. Returns as a string so
// leading zeros are preserved (000123 is a valid code).
export function generateOtpCode(): string {
  const n = Math.floor(Math.random() * 1_000_000)
  return n.toString().padStart(6, '0')
}

// Plain magic-link token creation (admin flow). P5 admin endpoint still
// doesn't need pairToken / code — only the public flow does.
export async function createMagicToken(
  identifier: string,
): Promise<{ token: string; expiresAt: Date }> {
  const token = createId()
  const expires = new Date(Date.now() + TOKEN_TTL_MS)
  await prisma.verificationToken.create({
    data: { identifier, token, expires },
  })
  return { token, expiresAt: expires }
}

// Create a new magic-link + pairToken + code row. PairToken is opaque to
// the server (just a UUID the browser generated and stashed in localStorage).
export async function createMagicTokenAndCode(
  identifier: string,
  pairToken: string,
): Promise<{ token: string; code: string; expiresAt: Date }> {
  const token = createId()
  const code = generateOtpCode()
  const expires = new Date(Date.now() + TOKEN_TTL_MS)
  await prisma.verificationToken.create({
    data: { identifier, token, pairToken, code, expires },
  })
  return { token, code, expiresAt: expires }
}

// Read-only check for token in URL — does NOT consume.
export async function peekMagicToken(token: string): Promise<ConsumeResult> {
  if (!token) return { ok: false, reason: 'not-found' }
  const row = await prisma.verificationToken.findUnique({ where: { token } })
  if (!row) return { ok: false, reason: 'not-found' }
  if (row.expires < new Date()) {
    await prisma.verificationToken.delete({ where: { token } }).catch(() => {})
    return { ok: false, reason: 'expired' }
  }
  if (row.consumed) return { ok: false, reason: 'already-consumed' }
  return { ok: true, identifier: row.identifier }
}

// Atomic check-and-consume: flips `consumed=true` instead of deleting so
// the row stays queryable by pairToken for cross-browser pairing.
// Old call sites that expected DELETE behaviour still work because the
// `consumed=true` flag prevents reuse — peekMagicToken returns
// 'already-consumed' on subsequent calls.
export async function consumeMagicToken(token: string): Promise<ConsumeResult> {
  const peek = await peekMagicToken(token)
  if (!peek.ok) return peek
  await prisma.verificationToken.update({
    where: { token },
    data: { consumed: true },
  })
  return peek
}

// Mark `paired=true` on a row by token. Called by /api/auth/public/verify
// BEFORE consuming, so browser A's polling can find the pairing.
export async function markPaired(token: string): Promise<boolean> {
  const row = await prisma.verificationToken.findUnique({ where: { token } })
  if (!row) return false
  if (row.expires < new Date()) return false
  if (row.consumed) return false
  await prisma.verificationToken.update({
    where: { token },
    data: { paired: true },
  })
  return true
}

// Find the VerificationToken row by pairToken. Used by browser A polling.
// Caller decides what to do based on paired/consumed/expires flags.
export async function findByPairToken(pairToken: string) {
  return prisma.verificationToken.findUnique({ where: { pairToken } })
}

// Atomic OTP code consumption: find by identifier + code, mark consumed.
export async function consumeMagicCode(identifier: string, code: string): Promise<ConsumeResult> {
  if (!code || !/^\d{6}$/.test(code)) return { ok: false, reason: 'not-found' }
  // Most-recent first to prefer the latest code over a still-valid older one.
  const row = await prisma.verificationToken.findFirst({
    where: { identifier, code },
    orderBy: { expires: 'desc' },
  })
  if (!row) return { ok: false, reason: 'not-found' }
  if (row.expires < new Date()) {
    await prisma.verificationToken.delete({ where: { token: row.token } }).catch(() => {})
    return { ok: false, reason: 'expired' }
  }
  if (row.consumed) return { ok: false, reason: 'already-consumed' }
  await prisma.verificationToken.update({
    where: { token: row.token },
    data: { consumed: true },
  })
  return { ok: true, identifier: row.identifier }
}

export async function purgeExpiredTokens(): Promise<number> {
  const result = await prisma.verificationToken.deleteMany({
    where: { expires: { lt: new Date() } },
  })
  return result.count
}